#!/bin/bash
#export UTAU=/home/sasukeuchiha/Music/Camila\ Melodia\ Act2
export UTAU=tests
#gdb --args ./timidity/timidity --preserve-silence /home/sasukeuchiha/Music/evaop_karaoke.mid
gdb --args ./timidity/timidity --preserve-silence tests/test1.mid -Ow
#audacity tests/test1.wav
