#!/bin/bash
export UTAU=/home/sasukeuchiha/Music/Camila\ Melodia\ Act2
#export UTAU=vox
../../abcmidi-20070318/abc2midi $1
B=$(basename $1 .abc)
mv $B\1.mid $B.mid
rm $B.wav
gdb --args ../timidity/timidity --preserve-silence $B.mid -Ow
audacity $B.wav
